env:
  browser: false
  node: true
  commonjs: true
  es2021: true
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - off
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
extends:
  - 'eslint:recommended'
  - 'prettier'
